# Generated by Django 5.1.15 on 2026-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, default='', help_text='e.g., 750 ml, 1 L, 500 g', max_length=50),
        ),
    ]
