# Generated by Django 5.1.15 on 2026-08-21 19:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='base_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='remaining_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MonthlyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('base_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_added', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_inventories', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Monthly Inventories',
                'unique_together': {('product', 'month')},
            },
        ),
    ]
