# Generated by Django 5.1.15 on 2026-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockhistory_base_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='change_type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('USE', 'USE'), ('SET_BASE', 'SET_BASE')], max_length=10),
        ),
    ]
