# Generated by Django 5.1.15 on 2026-08-21 21:50

from django.db import migrations, models


def make_cost_nullable(apps, schema_editor):
    """Rebuild SQLite's existing Product table with a nullable cost column."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(inventory_product)")
        existing_columns = {column[1] for column in cursor.fetchall()}
        cost_value = "cost" if "cost" in existing_columns else "NULL"

        cursor.execute(
            """
            CREATE TABLE inventory_product__new (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                name varchar(255) NOT NULL,
                category varchar(50) NOT NULL,
                unit varchar(50) NOT NULL,
                cost decimal NULL,
                supplier varchar(255) NOT NULL,
                is_active bool NOT NULL,
                product_size varchar(50) NOT NULL
            )
            """
        )
        cursor.execute(
            f"""
            INSERT INTO inventory_product__new
                (id, name, category, unit, cost, supplier, is_active, product_size)
            SELECT id, name, category, unit, {cost_value}, supplier, is_active, product_size
            FROM inventory_product
            """
        )
        cursor.execute("DROP TABLE inventory_product")
        cursor.execute("ALTER TABLE inventory_product__new RENAME TO inventory_product")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockhistory_change_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(make_cost_nullable, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='cost',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
    ]
