# Generated by Django 5.1.15 on 2026-08-22 12:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def populate_daily_inventories(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    StockHistory = apps.get_model('inventory', 'StockHistory')
    DailyInventory = apps.get_model('inventory', 'DailyInventory')
    MonthlyInventory = apps.get_model('inventory', 'MonthlyInventory')
    
    for product in Product.objects.all():
        history_entries = StockHistory.objects.filter(product=product).order_by('created_at')
        daily_transactions = {}
        for entry in history_entries:
            d = entry.created_at.date()
            if d not in daily_transactions:
                daily_transactions[d] = []
            daily_transactions[d].append(entry)
            
        for d, entries in daily_transactions.items():
            last_entry = entries[-1]
            base_stock = last_entry.base_stock if last_entry.base_stock is not None else Decimal('0.00')
            closing_stock = last_entry.new_quantity
            
            DailyInventory.objects.get_or_create(
                product=product,
                date=d,
                defaults={
                    'base_stock': base_stock,
                    'closing_stock': closing_stock
                }
            )
            
        if not history_entries.exists():
            try:
                inventory = product.inventory
                d = inventory.updated_at.date()
                month_start = d.replace(day=1)
                monthly_inv = MonthlyInventory.objects.filter(product=product, month=month_start).first()
                base_stock = monthly_inv.base_stock if monthly_inv else Decimal('0.00')
                closing_stock = inventory.current_quantity
                
                DailyInventory.objects.get_or_create(
                    product=product,
                    date=d,
                    defaults={
                        'base_stock': base_stock,
                        'closing_stock': closing_stock
                    }
                )
            except Exception:
                pass


def reverse_func(apps, schema_editor):
    DailyInventory = apps.get_model('inventory', 'DailyInventory')
    DailyInventory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventories', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Daily Inventories',
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.RunPython(populate_daily_inventories, reverse_func),
    ]

