# Generated by Django 5.1.15 on 2026-08-25 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_configure_history_spreadsheets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('branch_code', models.CharField(blank=True, default='', max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refill_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='inventory.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='inventory.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Refill Request',
                'verbose_name_plural': 'Inventory Refill Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
