# Generated by Django 5.1.15 on 2026-08-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_inventory_refill_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrefillrequest',
            name='base_stock',
        ),
        migrations.RemoveField(
            model_name='inventoryrefillrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryrefillrequest',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='inventoryrefillrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventoryrefillrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryrefillrequest',
            name='refill_required',
        ),
        migrations.CreateModel(
            name='InventoryRefillRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refill_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryrefillrequest')),
            ],
        ),
    ]
